name: Markdown Link Checker

on:
  push:
    branches:
      - ci-links
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Run markdown link check with verbose output
      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: true
          config-file: .github/link-check-config.json
