name: Check Links

on:
  push:
    branches:
      - ci-links

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: true
          config-file: .github/link-check-config.json
